### ISSUE TITLE
LINQ Expression could not be translated

### ISSUE THREAD

**Issue by datnguyen0126** [PacktPublishing/CSharp-8.0-and-.NET-Core-3.0-Modern-Cross-Platform-Development-Third-Edition#1]
At Chapter11/WorkingWithEFCore project, when I executed QueryingProducts() function, an exception was thrown as below
`Unhandled exception. System.InvalidOperationException: The LINQ expression 'Where<Product>(source: Where<Product>(source: DbSet<Product>, predicate: (p) => !(p.Discontinued)), predicate: (p) => p.Cost > (Unhandled parameter: __price_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.`

> running on Ubuntu 18.04, .Net Core 3.1 with Visual Studio Code

Could you check it again?
**Update:** I have fixed this by changing from 'decimal' to 'int' in Product.Cost

**Comment by thanhbao0408** [comment]
It's a breaking change with EF Core in .NET core as is shown here [](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#linq-queries-are-no-longer-evaluated-on-the-client).
We can no longer use the client evaluated. In your case, query with a **decimal** type
I think the author forgot to migrate the code from the older version.

**Comment by markjprice** [comment]
https://github.com/markjprice/cs8dotnetcore3/blob/master/errata.md#page-375---filtering-and-sorting-products

**Comment by gaurav-packt** [comment]
Closing the issue as author has shared the feedback
